Resolve #11 Add final-fidelity constraint to SDK
QuTech-Delft/netqasm pull request #13
Opened 2022-01-31 16:25 UTC by bvdvecht

2022-02-15 11:18 UTC, bvdvecht commented
Closes #11

2022-02-21 11:46 UTC, QFer requested changes

2022-02-21 11:46 UTC, QFer commented on netqasm/sdk/build_nv.py
> +        return 100_000 - min_fidelity * 900
With the right input this can become negative. Is the resulting behavior defined? Don't you wanna add a guard (maybe an assert) to it?

2022-02-21 11:46 UTC, QFer commented on netqasm/sdk/build_types.py
> +    @property
Because comm_qubit_count and mem_qubit_count properties are identical for all specific classes (subclasses of HardwareConfig), these methods can/should be part of the base class HardwareConfig (instead of the 2 properties raising notimplementederror).
When HardwareConfig also has an init, even the assert can be in there

2022-02-21 11:46 UTC, QFer commented on netqasm/sdk/builder.py
>              # evalute body (will add pending commands)
evalute -> evaluate

2022-02-21 11:46 UTC, QFer commented on netqasm/sdk/constraint.py
> +        """ValueAtMostContraint constructor.
Typo in classname:  s missing

2022-02-21 11:46 UTC, QFer commented on netqasm/sdk/build_types.py
> +class HardwareConfig:
I suspect (not 100% sure) this can be an abstract baseclass

2022-02-22 10:08 UTC, bvdvecht commented on netqasm/sdk/build_nv.py
> +        return 100_000 - min_fidelity * 900
Added an assert

2022-02-22 10:09 UTC, bvdvecht commented on netqasm/sdk/build_types.py
> +    @property
Re-organized these classes a bit.

2022-02-22 10:10 UTC, bvdvecht commented on netqasm/sdk/builder.py
>              # evalute body (will add pending commands)
Fixed

2022-02-22 10:10 UTC, bvdvecht commented on netqasm/sdk/constraint.py
> +        """ValueAtMostContraint constructor.
Fixed

2022-02-22 10:10 UTC, bvdvecht commented on netqasm/sdk/build_types.py
> +class HardwareConfig:
Made it an abstract base class

2022-02-22 10:31 UTC, bvdvecht commented
@QFer Implemented your feedback.

2022-02-23 11:54 UTC, QFer approved these changes

2022-02-23 12:15 UTC, merged